server:
  port: 9080
spring:  application:    name: springcloud-config   #定义服务的名称
  cloud:    config:      server:        git:          uri: https://github.com/LeonJay1114/student_config.git
          #连接远程github账户
